version: 2
jobs:
  syntax_check:
    working_directory: ~/narratepy
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: addFlake8
          command: sudo pip install flake8
      - run:
          name: pep8Check
          command: sudo flake8 --max-complexity 10